import { Cake } from "./cake";

export const CAKES: Cake[] = [
    { id: 1,price:500,img:"assets/Images/choco/1.jpg", name: 'Dainty Black Forest Cake' },
    { id: 2,price:550,img:"assets/Images/choco/2.jpg", name: 'Extravagant Truffle Cake' },
    { id: 3,price:600,img:"assets/Images/choco/3.jpg", name: 'Fuse Fiesta' },
    { id: 4,price:600,img:"assets/Images/choco/4.jpg", name: 'Ebony And Ivory' },
    { id: 5,price:650,img:"assets/Images/choco/5.jpg", name: 'Chocoholick Delight' },
    { id: 6,price:750,img:"assets/Images/choco/6.jpg", name: 'The Original B.F.' },
    { id: 7,price:450,img:"assets/Images/choco/7.jpg", name: 'Choco-Thrill' },
    { id: 8,price:500,img:"assets/Images/choco/8.jpg", name: 'The Chocolateria' },
    { id: 9,price:500,img:"assets/Images/choco/9.jpg", name: 'Delectable Truffle' },
    { id: 10,price:600,img:"assets/Images/choco/10.jpg", name: 'Chocolate Orange Delight' },
    { id: 11,price:500,img:"assets/Images/choco/11.jpg", name: 'Choco Tranquiizer' },
    { id: 12,price:500,img:"assets/Images/choco/12.jpg", name: 'Chocoholique Dream' },
    { id: 13,price:550,img:"assets/Images/choco/13.jpg", name: 'German Gateau' },
    { id: 14,price:700,img:"assets/Images/choco/14.jpg", name: 'Sweetest Appeal' },
    { id: 15,price:600,img:"assets/Images/choco/15.jpg", name: 'Amore Mio' },
    { id: 16,price:550,img:"assets/Images/fruit/1.jpg", name: 'Pink Heaven' },
    { id: 17,price:500,img:"assets/Images/fruit/2.jpg", name: 'Luxurious Fantasy' },
    { id: 18,price:500,img:"assets/Images/fruit/3.jpg", name: 'Chocolate Truffle Fruit Cake' },
    { id: 19,price:500,img:"assets/Images/fruit/4.jpg", name: 'Fruit Fully Yours' },
    { id: 20,price:500,img:"assets/Images/fruit/5.jpg", name: 'Ecstatically Delicious' },
    { id: 21,price:500,img:"assets/Images/fruit/6.jpg", name: 'Kiwi-Licious' },
    { id: 22,price:500,img:"assets/Images/fruit/7.jpg", name: 'Fruit Frenzy' },
    { id: 23,price:500,img:"assets/Images/fruit/8.jpg", name: 'Fruit By Nature' },
    { id: 24,price:500,img:"assets/Images/fruit/9.jpg", name: 'Cherry-Indulgence' },
    { id: 25,price:550,img:"assets/Images/strawberry/1.jpg", name: 'External Berry Love' },
    { id: 26,price:500,img:"assets/Images/strawberry/2.jpg", name: 'Pink Heaven' },
    { id: 27,price:500,img:"assets/Images/strawberry/3.jpg", name: 'Shades of Love' },
    { id: 28,price:500,img:"assets/Images/strawberry/4.jpg", name: 'Luscious Chocoberry' },
    { id: 29,price:500,img:"assets/Images/strawberry/5.jpg", name: 'Strawberry Seduction' },
    { id: 30,price:500,img:"assets/Images/strawberry/6.jpg", name: 'Motherly Love' },
    { id: 31,price:500,img:"assets/Images/strawberry/7.jpg", name: 'Eternal Sweetness' },
    { id: 32,price:560,img:"assets/Images/strawberry/8.jpg", name: 'Secret Confession' },
    { id: 33,price:500,img:"assets/Images/strawberry/9.jpg", name: 'Celebratory Swirls' },
    { id: 34,price:550,img:"assets/Images/vanilla/1.jpg", name: 'Vegan vanilla' },
    { id: 35,price:500,img:"assets/Images/vanilla/2.jpg", name: 'Vanilla Retreat' },
    { id: 36,price:500,img:"assets/Images/vanilla/3.jpg", name: 'Choco Vanilla Cake' },
    { id: 37,price:500,img:"assets/Images/vanilla/4.jpg", name: 'Torrid Affair' },
    { id: 38,price:500,img:"assets/Images/vanilla/5.jpg", name: 'Two in One' },
    { id: 39,price:500,img:"assets/Images/vanilla/6.jpg", name: 'Floral Fun' },
    { id: 40,price:500,img:"assets/Images/vanilla/7.jpg", name: 'Snow kissed' },
    { id: 41,price:560,img:"assets/Images/vanilla/8.jpg", name: 'Secrete Confession' },
    { id: 42,price:500,img:"assets/Images/vanilla/9.jpg", name: 'Vanilla Rush' },
    { id: 43,price:550,img:"assets/Images/butter/1.jpg", name: 'Butterscotch Delight' },
    { id: 44,price:500,img:"assets/Images/butter/2.jpg", name: 'Butterscotch Obesession' },
    { id: 45,price:500,img:"assets/Images/butter/3.jpg", name: 'Choco-Scotch Sensation' },
    { id: 46,price:500,img:"assets/Images/butter/4.jpg", name: 'Dreamy Creamy Opulence' },
    { id: 47,price:500,img:"assets/Images/butter/5.jpg", name: 'Flavorsome Fuse' },
    { id: 48,price:500,img:"assets/Images/butter/6.jpg", name: 'From Heart to Mouth' },
    { id: 48,price:500,img:"assets/Images/mango-cheese-cake-A.jpg", name: 'Sunshine Poise' },
    { id: 50,price:500,img:"assets/Images/tom-n-jerry-poster-cake-phot1344flav-A.jpg", name: 'Tom and Jerry' },
    { id: 51,price:500,img:"assets/Images/Bakingo-Mom-Dad-Anniversary-Poster-cake-2-b.jpg", name: 'Anniversery cakes' },
    { id: 52,price:560,img:"assets/Images/strawberry/8.jpg", name: 'Avengers' },
    { id: 53,price:500,img:"assets/Images/baby-shower-cake-1-A.jpg", name: 'Baby Shower cakes' },
    { id: 54,price:550,img:"assets/Images/photo-cake-for-birthday-phot1124flav-B.jpg", name: 'Delight Birthday cakes' },
    { id: 55,price:500,img:"assets/Images/pubg-battleground-poster-cake-phot1127flav-B.jpg", name: 'PUBG battleground' },
    { id: 56,price:500,img:"assets/Images/spiderman.jpg", name: 'Spider Man' },
    { id: 57,price:500,img:"assets/Images/rainbow.jpg", name: 'Rainbow cakes' },
    { id: 58,price:500,img:"assets/Images/babyshower.jpg", name: 'Baby shower' },
    { id: 59,price:500,img:"assets/Images/mickeymouse.jpg", name: 'mickey mouse' },
    { id: 60,price:500,img:"assets/Images/pubg_1.jpg", name: 'PUBG cakes' },
    { id: 61,price:560,img:"assets/Images/minion.jpg", name: 'minion cakes' },
    { id: 62,price:500,img:"assets/Images/bheem.jpg", name: 'Chhota Bheem' },
    { id: 63,price:550,img:"assets/Images/cartoon.jpg", name: 'Cartoon cakes' },
    { id: 64,price:500,img:"assets/Images/exotic/3.jpg", name: 'Red Infatuation' },
    { id: 65,price:500,img:"assets/Images/exotic/4.jpg", name: 'Oh So Orange Licious' },
    { id: 66,price:500,img:"assets/Images/exotic/5.jpg", name: 'Tropilicious Treat' },
    { id: 67,price:500,img:"assets/Images/exotic/6.jpg", name: 'Paan Cake' },
    { id: 68,price:500,img:"assets/Images/exotic/7.jpg", name: 'Funfetti Rainbow Tower' },    
    { id: 69,price:500,img:"assets/Images/exotic/8.jpg", name: 'Kit Kat "Bake"' },    
    { id: 70,price:500,img:"assets/Images/exotic/9.jpg", name: 'Rocher-AholicS Fantasy' },



  ];